/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package favoritebooks;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        Author = new javax.swing.JLabel();
        Award = new javax.swing.JLabel();
        Rating = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        Pages = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        TitleF = new javax.swing.JTextField();
        CategoryF = new javax.swing.JTextField();
        AuthorF = new javax.swing.JTextField();
        AwardF = new javax.swing.JTextField();
        YearF = new javax.swing.JTextField();
        PagesF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionF = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        add1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Title.setText("Title");

        Category.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Category.setText("Category");

        Author.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Author.setText("Author Name and Surname");

        Award.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Award.setText("Award Winner");

        Rating.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Rating.setText(" Rating");

        Year.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Year.setText(" Year");

        Pages.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Pages.setText("Number of Pages");

        Description.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Description.setText("Description");

        DescriptionF.setColumns(20);
        DescriptionF.setRows(5);
        jScrollPane1.setViewportView(DescriptionF);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        add1.setText("Back to Menu");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Category, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Author, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Award, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rating, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Year, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pages, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AwardF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TitleF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CategoryF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(AuthorF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PagesF)
                        .addComponent(YearF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(TitleF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Author))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AwardF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Award))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rating))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PagesF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(add1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public int calculateId() throws FileNotFoundException{
        
        BufferedReader b = new BufferedReader(new FileReader("books.txt"));
        String line= null;
        String result= "";
        int id=0;
       
        try{
            while((line =b.readLine()) != null)
            {
                String[] elements = line.split("\n");
                for(String str : elements){
                     result = "";
                    result += str + "\n";
                }

            }
            b.close();
           
            String[] elements = result.split(",");
            String a = elements[0];
            id = Integer.parseInt(a)+1;
           }
        
        catch(IOException ex){
            System.out.println("Error - file open");
        }
        
        return id;
   
    }
    public static boolean isNumeric(String string) {
    int intValue;
		
   
		
    if(string == null || string.equals("")) {
       JOptionPane.showMessageDialog(null, "You must enter a number for the year or the number of pages");
        return false;
    }
    
    try {
        intValue = Integer.parseInt(string);
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "You must enter a number for the year or the number of pages");
    }
    return false;
}
    
    
    
    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
         AfterLogIn afterlogIn = new AfterLogIn();
         this.setVisible(false);
         afterlogIn.setVisible(true);
         afterlogIn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_add1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(!TitleF.getText().isEmpty()&&!AuthorF.getText().isEmpty()&& !AwardF.getText().isEmpty()&&!CategoryF.getText().isEmpty()&&!DescriptionF.getText().isEmpty()
                && !PagesF.getText().isEmpty()&& !YearF.getText().isEmpty()){
                
            
                 String year = YearF.getText();
                 String pages = PagesF.getText();
                 
                 
                 if(isNumeric(year) && isNumeric(pages)){
                 
                 String title = TitleF.getText();
                 String category = CategoryF.getText();
                 String author = AuthorF.getText();
                 String award = AwardF.getText();
                 String rating = String.valueOf(jComboBox1.getSelectedItem());
                 
                 String description = DescriptionF.getText();
                 int id =0;
                 try{
                      id = calculateId();
                            
                 }
                 catch (FileNotFoundException ex)
                 {
                     System.out.println("Error - file open");
                 }
                 
                 int A = Integer.parseInt(YearF.getText());
                 int B = Integer.parseInt(PagesF.getText());
                 
                 if(1900<=A && A<=2021 && B>0){
                     try
                     {
                         FileWriter Writer = new FileWriter("books.txt", true);
                         Writer.write(id+ ","+title + "," + category + ","+ author +","+ award+ ","+ rating+ ","+ year+ ","+pages+ ","+ description);
                         Writer.write(System.getProperty("line.separator"));
                         Writer.close();
                         JOptionPane.showMessageDialog(null, "The book has been successfully added to the list.");
                         setVisible(false);
                         new AddBook().setVisible(true);
                     }
                     catch(Exception e){
                          JOptionPane.showMessageDialog(null,"Error! Try again please.");
                         
                     }
                }
                else {
                     JOptionPane.showMessageDialog(null,"You entered wrong year or number of page.");
                 }
                     
                 }  
        }
        else {
            JOptionPane.showMessageDialog(null,"You left a field blank. Please try again.");
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JTextField AuthorF;
    private javax.swing.JLabel Award;
    private javax.swing.JTextField AwardF;
    private javax.swing.JLabel Category;
    private javax.swing.JTextField CategoryF;
    private javax.swing.JLabel Description;
    private javax.swing.JTextArea DescriptionF;
    private javax.swing.JLabel Pages;
    private javax.swing.JTextField PagesF;
    private javax.swing.JLabel Rating;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TitleF;
    private javax.swing.JLabel Year;
    private javax.swing.JTextField YearF;
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

